KLJUC = "Kljuc: "
ODABERI = "Odaberi"
PREGLEDAJ = "Pregledaj"
GENERIRAJ = "Generiraj"
KRIPTIRAJ = "Kriptiraj"
DEKRIPTIRAJ = "Dekriptiraj"
ULAZNA_DATOTEKA = "Ulazna datoteka: "
IZLAZNA_DATOTEKA = "Izlazna datoteka: "
JAVNI_KLJUC_PRIMATELJA = "Javni kljuc primatelja: "
DIGITALNA_OMOTNICA = "Digitalna omotnica: "
TAJNI_KLJUC_PRIMATELJA = "Tajni kljuc primatelja: "
GENERIRAJ_DIGITALNU_OMOTNICU = "Generiraj digitalnu omotnicu"
OTVORI_DIGITALNU_OMOTNICU = "Otvori digitalnu omotnicu"
TAJNI_KLJUC_POSILJATELJA = "Tajni kljuc posiljatelja: "
JAVNI_KLJUC_POSILJATELJA = "Javni kljuc posiljatelja: "
GENERIRAJ_DIGITALNI_POTPIS = "Generiraj digitalni potpis"
PROVJERI_DIGITALNI_POTPIS = "Provjeri digitalni potpis"
DIGITALNI_POTPIS = "Digitalni potpis: "
DIGITALNI_PECAT = "Digitalni pecat: "
GENERIRAJ_DIGITALNI_PECAT = "Generiraj digitalni pecat"
OTVORI_DIGITALNI_PECAT = "Otvori digitalni pecat"
TAJNI_KLJUC = "Tajni kljuc: "
JAVNI_KLJUC = "Javni kljuc: "
VLASNIK = "Igor Farszky"
GENERIRAJ_KLJUCEVE = "Generiraj kljuceve"
SAZETAK = "Sazetak: "
GENERIRAJ_SAZETAK = "Generiraj sazetak"
BLOK_128_T = "128"
BLOK_192_T = "192"
BLOK_256_T = "256"
BLOK_128 = 128
BLOK_192 = 192
BLOK_256 = 256
RSA_1024_T = "1024"
RSA_2048_T = "2048"
RSA_4096_T = "4096"
RSA_1024 = 1024
RSA_2048 = 2048
RSA_4096 = 4096
ULAZ_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\ulaz.txt'
IZLAZ_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\izlaz.txt'
DES_IZLAZ_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\des_izlaz.txt'
DES_KLJUC_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\des_kljuc.txt'
DES_ULAZ_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\des_ulaz.txt'
OMOTNICA_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\omotnica.txt'
PECAT_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\pecat.txt'
POTPIS_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\potpis.txt'
RSA_A_JAVNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_a_javni.txt'
RSA_B_JAVNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_b_javni.txt'
RSA_B_TAJNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_b_tajni.txt'
RSA_A_TAJNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_a_tajni.txt'
RSA_JAVNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_javni.txt'
RSA_TAJNI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\rsa_tajni.txt'
SAZETAK_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\sazetak.txt'
DOKUMENTI_PATH = 'C:\\Users\\Igor Farszky\\PycharmProjects\\NOS_digitalni_pecat\\dokumenti\\'